### ISSUE TITLE
Compatibility with Seurat V3

### ISSUE THREAD

**Issue by angelussong** [kevyu27/CellFindR#1]
Hi Dr. yu, 

Sorry to bug you with this. I am working on a single-cell RNA-seq analysis project and trying to investigate the resolution of my current cell type clustering to see if it's possible to identify more groups with distinct expression profiles. 

However, I was using Seurat V3 for my analysis (PCA, KNN, UMAP). I modified some of your code to make it compatible with Seurat V3 and here is a little run down of my procedure: I loaded an established Seurat object, in which I have already done an initial clustering and run TSNE/UMAP. Then as I tried to run the run_clustering() I made it through the first cluster (cluster 0) before running into an error with FindMarkers() in this line: 
markers <- FindMarkers(tenx, ident.1 = j, min.pct = 0.25).

This is my output: 

run_clustering(tenx, file_dest, dir_add)
[1] 0
PC_ 1 
Positive:  TRBC2, CCL5, CD3D, CD2, CD96, IL7R, SPOCK2, ETS1, TRAC, CD8A 
	   CXCR4, CD69, CD3G, LCK, PTPRCAP, TNFAIP3, ICOS, CD247, BCL11B, CD3E 
	   ITK, IL2RB, RP11-94L15.2, ITGAL, FYB, IFNG, GZMA, RORA, PTGER4, CD6 
Negative:  PSAP, SEPP1, DSP, CD9, AZGP1, TACSTD2, CPE, KLK3, PTPRF, NFIB 
	   TSC22D1, KLK2, CTSB, NKX3-1, KLF4, RBM47, CD59, TBX3, ADIRF, STEAP2 
	   H1F0, ALDH1A3, CKB, TSPAN1, GRN, SPINT2, FXYD3, ATP8B1, EHF, DST 
PC_ 2 
Positive:  CCL4, KLRD1, GZMB, PRF1, GZMH, CD8A, GNLY, CCL5, NKG7, IFNG 
	   XCL2, FASLG, MYBL1, ZNF683, XCL1, HOPX, FCRL6, FGFBP2, CD8B, KLRC1 
	   GZMA, ITGA1, SLAMF7, TRGC2, CRTAM, AUTS2, RASGEF1B, EOMES, CD160, TRDC 
Negative:  CTLA4, CCR4, CD28, TNFRSF4, FOXP3, LTB, BATF, IL2RA, RTKN2, CD40LG 
	   SPOCK2, CCR7, TNFRSF18, CD5, CD4, SIRPG, MAF, ICOS, PIK3IP1, TRAT1 
	   CD27, DUSP4, IL7R, TNFRSF9, MAL, TRABD2A, PHLDA1, SMAP2, BCL11B, LEF1 
PC_ 3 
Positive:  ITGA1, IL7R, SCML4, SPRY1, JUN, ZNF683, KLRC1, TNF, IFNG, XCL1 
	   FOSB, CD101, CD69, AMICA1, PFKFB3, PTGER4, CAMK4, NR4A1, THEMIS, FASLG 
	   IL2, GPR171, CITED2, EGR2, CD8A, LDLRAD4, NKRF, SLC4A10, ID2, CD96 
Negative:  FGFBP2, NKG7, GNLY, PRF1, S1PR5, GZMA, KLRG1, GZMK, GZMH, FCRL6 
	   KLRF1, CD247, GZMB, TRDC, TIGIT, FCRL3, P2RY8, FAM65B, SYNE1, ITGB2 
	   RUNX3, B3GNT7, CX3CR1, SH2D1A, IL2RB, PLEK, ENC1, TXK, EOMES, NCAM1 
PC_ 4 
Positive:  IL17A, SLC4A10, PPP1R16B, LTK, KLRB1, CD40LG, RORA, LTB, B3GALT2, TNF 
	   TMIGD2, ICOS, CA10, NR4A2, SPOCK2, ITGA4, MAN1A1, ADAM12, CXCR6, FASLG 
	   PPARG, NCR3, NR4A3, EGR2, IL23R, ATP2B4, KLF12, FAM46C, CAMK4, TSC22D2 
Negative:  HSPE1, CACYBP, HSPA6, ZFAND2A, DOK2, DNAJB4, HSPA1A, MIR24-2, HSPD1, ISG20 
	   HSPA1B, GZMH, TXNIP, KLRC2, HSPH1, GZMB, KLRD1, BAG3, PMAIP1, HMGB2 
	   DNAJA4, MYADM, SERPINH1, DNAJB1, SOCS1, FKBP5, CYTIP, CD8B, KLRC1, JUND 
PC_ 5 
Positive:  CD8A, AUTS2, CD8B, KLRC1, GZMB, SAMSN1, DUSP4, TNFRSF1B, P2RY10, LDLRAD4 
	   CXCR6, IRF4, CLEC2B, ITGA1, PTPN22, AP000783.1, CD3E, MTRNR2L1, ATP1B3, CD96 
	   CLIC5, PPP1R16B, ITM2A, FTH1, CD3D, KPNA2, CCL5, SCUBE1, GZMH, FAM46C 
Negative:  TNF, EOMES, CD40LG, IFNG, FASLG, TAGAP, JUN, FOS, KLRG1, HSPA1B 
	   GADD45B, NR4A1, EGR2, DUSP1, SLAMF1, FOSB, FGFBP2, ZFP36L1, SLC4A10, CD69 
	   TXNIP, CCL4, SLFN5, NCR3, CITED2, TSC22D2, LCP2, FAM65B, PPP1R15A, IER2 
Computing nearest neighbor graph
Computing SNN
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 1558
Number of edges: 120730

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.9059
Number of communities: 2
Elapsed time: 0 seconds
[1] "0"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=08s  
[1] "2"
[1] "1"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=09s  
[1] "2"
[1] "ok 0.1"
Computing nearest neighbor graph
Computing SNN
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 1558
Number of edges: 120730

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.8197
Number of communities: 6
Elapsed time: 0 seconds
[1] "0"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
[1] "2"
[1] "1"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
[1] "2"
[1] "2"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=03s  
[1] "2"
[1] "3"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=08s  
[1] "2"
[1] "4"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07s  
[1] "2"
[1] "5"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07s  
[1] "2"
[1] "broke 0.3"
[1] 0.1
[1] 0.1
[1] "Subclustering!"
Computing nearest neighbor graph
Computing SNN
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 1558
Number of edges: 120730

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.9059
Number of communities: 2
Elapsed time: 0 seconds
[1] "Doing Subgroups!"
Saving 7 x 7 in image
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=08s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=09s  
[1] "output2019-10-21 23:20:15/seqwell_prostate_0_matrix.csv"
Calculating cluster 0
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04s  
Calculating cluster 1
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04s  
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
[1] "0  0"
PC_ 1 
Positive:  PSAP, SEPP1, DSP, CD9, AZGP1, TACSTD2, CPE, KLK3, PTPRF, NFIB 
	   TSC22D1, KLK2, NKX3-1, CTSB, KLF4, RBM47, CD59, TBX3, ADIRF, H1F0 
	   STEAP2, ALDH1A3, CKB, TSPAN1, ATP8B1, GRN, FXYD3, SPINT2, EHF, DST 
Negative:  TRBC2, CCL5, CD96, CD3D, CD2, IL7R, SPOCK2, TRAC, ETS1, CXCR4 
	   CD8A, CD69, CD3G, ICOS, LCK, TNFAIP3, BCL11B, CD3E, PTPRCAP, ITK 
	   RP11-94L15.2, CD247, FYB, IL2RB, PTGER4, IFNG, RORA, THEMIS, CYTIP, CD6 
PC_ 2 
Positive:  CD8A, CCL4, IFNG, CCL5, XCL2, ZNF683, FASLG, ITGA1, XCL1, KLRC1 
	   KLRD1, CD8B, HOPX, GZMB, TRGC2, CRTAM, MYBL1, RASGEF1B, GZMH, AUTS2 
	   RP11-291B21.2, SPRY1, THEMIS, CD160, PRF1, KLRC2, CD101, SLAMF7, TNF, PTGER4 
Negative:  CCR4, CTLA4, FOXP3, TNFRSF4, CD28, IL2RA, RTKN2, LTB, BATF, TNFRSF18 
	   CCR7, CD5, CD4, SPOCK2, SIRPG, CD40LG, CD27, TRAT1, TNFRSF9, MAF 
	   GBP5, MAL, TIGIT, LEF1, DUSP4, PIK3IP1, TRABD2A, BTLA, SMC4, IKZF2 
PC_ 3 
Positive:  HSPE1, CACYBP, HSPA6, DNAJB4, HSPA1A, ZFAND2A, MIR24-2, DOK2, HSPD1, HSPA1B 
	   TXNIP, KLRC2, ISG20, HSPH1, BAG3, KLRD1, KLRC1, DNAJB1, FKBP5, MYADM 
	   DNAJA4, SERPINH1, HMGB2, GZMB, PMAIP1, SOCS1, CYTIP, GZMH, CD8B, JUND 
Negative:  PPP1R16B, IL17A, SLC4A10, RORA, LTK, B3GALT2, KLRB1, LTB, CD40LG, NR4A2 
	   ITGA4, TNF, CA10, SPOCK2, ICOS, NR4A3, FAM46C, ADAM12, MAN1A1, ATP2B4 
	   FASLG, CXCR6, PPARG, TMIGD2, RASGRP1, IL2RB, KLF12, GZMK, NCR3, BHLHE40 
PC_ 4 
Positive:  CD40LG, SLC4A10, IL7R, KLRB1, TMIGD2, LTK, IL17A, SCML4, TNF, LTB 
	   NCR3, SLAMF1, JUN, IFI44, B3GALT2, CD69, HSPA1B, CITED2, NR4A1, SPRY1 
	   IL23R, IL2, RORA, FOSB, NELL2, EGR2, DUSP1, CCL20, FOS, ID2 
Negative:  GZMK, TIGIT, CRTAM, DTHD1, GZMA, GZMH, DUSP4, TTN, SH2D1A, CD8A 
	   CD27, FCRL6, GZMB, TNFRSF9, CCL5, RUNX3, FCRL3, SLAMF7, NKG7, PRF1 
	   EOMES, CD8B, LYST, DUSP2, TNFRSF1B, ENC1, IL2RB, MTRNR2L1, GNLY, CCDC141 
PC_ 5 
Positive:  IFNG, GZMK, TNF, EOMES, FASLG, TAGAP, CCL4, DTHD1, GADD45B, JUN 
	   EGR2, FOS, NR4A1, XCL2, FOSB, CD27, HSPA1B, SH2D1A, DUSP1, KLRG1 
	   ARHGAP25, TIGIT, TSC22D2, SLFN5, ZFP36L1, LCP2, SLAMF1, CD69, FOXP3, RTKN2 
Negative:  AUTS2, GZMB, KLRC1, CXCR6, KLRB1, TMIGD2, CD8A, IL7R, LDLRAD4, RORA 
	   TNFRSF1B, CLEC2B, SPOCK2, P2RY10, AP000783.1, CD8B, PTPN22, PFKFB3, PER1, PRF1 
	   CD96, FTH1, IRF4, FKBP5, CLIC5, GPR65, GPR171, KLRD1, SAMSN1, CD3E 
Computing nearest neighbor graph
Computing SNN
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 1465
Number of edges: 115724

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.9000
Number of communities: 1
Elapsed time: 0 seconds
[1] "0"
Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : 
  Cell group 2 is empty - no cells with identity class 
In addition: There were 31 warnings (use warnings() to see them)

It seems that I was trying to find markers within the only cluster. I don't know if the previous Seurat could do that but now the FindMarkers() don't really allow it. I'm thinking if I can just add an if here to see if there's only one cluster then just output the top 10 or top 100 expressed genes as markers. 

Would you please help me with this?

Thanks, 

Hanbing Song

**Comment by kevyu27** [comment]
I know it is not convenient to use Seurat 1.4 however many of the function calls are different in Seurat 3 vs Seurat 1 (not only the findmarkers function). So I suspect that more errors will pop up. We are currently working on building a python version using scanpy for cellfindR. Please send me an email if you are interested but that should be posted online in the near future.

**Comment by kevyu27** [comment]
-Closed: now updated for Seurat 3.1
